name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  powershell:
    name: EnvVars
    runs-on: windows-latest
    steps:
      - name: List environment variables
        shell: powershell
        run: |
          Get-ChildItem Env:
